version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform

  build:
    commands:
      - echo "Formatting Terraform files..."
      - terraform fmt -recursive
      - echo "Running Terraform Init & Apply..."
      - terraform init -input=false
      - terraform apply -auto-approve -input=false

artifacts:
  files:
    - '**/*'