version: 0.2

phases:

  install:
    commands:
      - echo "Installing Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Validating Terraform..."
      - terraform validate

      - echo "Creating Terraform plan..."
      - terraform plan -out=tfplan

      - echo "Converting plan to readable output..."
      - terraform show -no-color tfplan > tfplan.txt

  post_build:
    commands:
      - echo "Terraform plan completed."

artifacts:
  files:
    - tfplan
    - tfplan.txt
    - '**/*.tf'
  discard-paths: no